version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
  backend:
    build: ./backend
    ports:
      - 4000:4000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/spendwise
      - BASE_URL=http://localhost:4000
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
volumes:
  mongodata:
